### ISSUE TITLE
Post Removal Request - UW Homework Solutions

### ISSUE THREAD

**Issue by jsanders89** [RohanGupta24/School-Projects#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington.  Some posts in this repository contain solution code to homework assignments identical to ours.

[Anagrams](https://courses.cs.washington.edu/courses/cse143/15au/homework/6/spec.pdf)
https://github.com/RohanGupta24/School-Projects/blob/master/Gupta%20Anagrams/Gupta%20Anagrams.java

[Grammar Solver](https://courses.cs.washington.edu/courses/cse143/15au/homework/4/spec.pdf)
https://github.com/RohanGupta24/School-Projects/blob/master/Gupta%20Grammar%20Solver%20FINAL/GrammarSolver.java

[Assassin](https://courses.cs.washington.edu/courses/cse143/15au/homework/3/spec.pdf)
https://github.com/RohanGupta24/School-Projects/blob/master/Gupta%20Assassin/AssassinManager.java

These posts' solution codes are indexed by Google, enabling our current students to easily find them and cheat on their assignments.

Would you please remove these posts or make them private in order to help us enforce our academic policy?

By removing them, you would be removing tools that our students could use in academic misconduct.

Thank you,
Jonathan Sanders
CSE 14X Program Coordinator
University of Washington
jsanders@cs.washington.edu

ps, if you sign up with your school email address, you can get free private repositories https://education.github.com/pack

**Comment by RohanGupta24** [comment]
Hello Jonathan,

Thanks for making me aware of the situation. The projects that you specified were past homework for my Introduction to Programming class in high school. As a result, I did not realize that the homework assignments were directly linked to college coursework.

Regards,

Rohan Gupta
B.S. in Computer Science, Purdue Univ.
gupta326@purdue.edu
(425) 614-7003
Expected Graduation Date: May 2020

**Comment by RohanGupta24** [comment]
I just made my repository private. Please let me know if you have any other concerns.
